#!/bin/bash
#
# andy-universal-agent-rules Installer
# One-liner installation for Linux/Mac
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/andiupn/andy-universal-agent-rules/main/install.sh | bash
#

set -e

REPO_URL="https://github.com/andiupn/andy-universal-agent-rules"
REPO_RAW="https://raw.githubusercontent.com/andiupn/andy-universal-agent-rules/main"

echo "🚀 Installing andy-universal-agent-rules..."
echo ""

# Check if .agent folder already exists
if [ -d ".agent" ]; then
    echo "⚠️  .agent folder already exists!"
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "❌ Installation cancelled."
        exit 1
    fi
    rm -rf .agent
fi

# Create .agent folder structure
echo "📁 Creating folder structure..."
mkdir -p .agent/scripts
mkdir -p .agent/memory/entries/{gotchas,patterns,decisions,context}
mkdir -p .agent/context
mkdir -p .agent/workflows

# Download scripts
echo "📥 Downloading scripts..."
SCRIPTS=(
    "save-knowledge.py"
    "search-knowledge.py"
    "validate-index.py"
    "backup-memory.py"
    "detect-environment.py"
    "sync-agents-stats.py"
)

for script in "${SCRIPTS[@]}"; do
    curl -sL "$REPO_RAW/.agent/scripts/$script" -o ".agent/scripts/$script"
    echo "   ✅ $script"
done

# Download context files
echo "📥 Downloading context files..."
curl -sL "$REPO_RAW/.agent/context/session-init.md" -o ".agent/context/session-init.md"
echo "   ✅ session-init.md"

# Download workflows (CORE FEATURE)
echo "📥 Downloading workflows..."
WORKFLOWS=(
    "maintenance.md"
    "maintenance-agent-rules.md"
    "save-from-chat.md"
    "search.md"
    "simpan-pengetahuan-dari-chat.md"
    "simpan-pengetahuan-dari-folder.md"
)

for workflow in "${WORKFLOWS[@]}"; do
    curl -sL "$REPO_RAW/.agent/workflows/$workflow" -o ".agent/workflows/$workflow" 2>/dev/null && \
        echo "   ✅ $workflow" || \
        echo "   ⚠️ Failed to download $workflow"
done

# Create empty index.json
echo "📝 Creating empty knowledge index..."
cat > .agent/memory/index.json << 'EOF'
{
  "version": "1.0.0",
  "lastUpdated": null,
  "totalEntries": 0,
  "categories": {
    "gotchas": {
      "description": "Production bugs & solutions",
      "count": 0,
      "entries": []
    },
    "patterns": {
      "description": "Code patterns that work",
      "count": 0,
      "entries": []
    },
    "decisions": {
      "description": "Architectural decisions",
      "count": 0,
      "entries": []
    },
    "context": {
      "description": "Project context & guides",
      "count": 0,
      "entries": []
    }
  }
}
EOF

# Create basic AGENTS.md if not exists
if [ ! -f "AGENTS.md" ]; then
    echo "📝 Creating AGENTS.md..."
    cat > AGENTS.md << 'EOF'
# AGENTS.md

> AI Agent Instructions for this project. Powered by andy-universal-agent-rules.

---

## 📋 Project Overview

**Project:** (auto-detected)
**Stack:** See `.agent/context/environment.json`

---

## ⚡ Quick Commands

```bash
# Save new knowledge
python .agent/scripts/save-knowledge.py --category gotchas "description"

# Search knowledge
python .agent/scripts/search-knowledge.py "keyword"

# Validate index
python .agent/scripts/validate-index.py --fix

# Backup memory
python .agent/scripts/backup-memory.py
```

---

## 🧠 Knowledge Categories

- **gotchas/** - Production bugs & fixes
- **patterns/** - Working code patterns
- **decisions/** - Architectural decisions
- **context/** - Project guides

---

## 🛡️ Safety Rules

### Always Confirm Before:
- Delete operations (`rm`, `DROP TABLE`, `TRUNCATE`)
- Git destructive (`reset --hard`, `clean -fd`, force push)
- Package installs (`npm install`, `composer require`)

### Never Access:
- `.env`, `.env.*`, `*.env`
- `*.pem`, `*.key`, `id_rsa`
- `credentials/*`, `secrets/*`

---

## 🔗 Memory System

Knowledge stored in `.agent/memory/entries/`

Search: `python .agent/scripts/search-knowledge.py "query"`

---

*Generated by andy-universal-agent-rules*
*GitHub: https://github.com/andiupn/andy-universal-agent-rules*
EOF
fi

# Run environment detection
echo ""
echo "🔍 Detecting environment..."
if command -v python3 &> /dev/null; then
    python3 .agent/scripts/detect-environment.py
elif command -v python &> /dev/null; then
    python .agent/scripts/detect-environment.py
else
    echo "⚠️  Python not found. Run 'python .agent/scripts/detect-environment.py' manually."
fi

echo ""
echo "✅ Installation complete!"
echo ""
echo "📚 Next steps:"
echo "   1. Read AGENTS.md for usage instructions"
echo "   2. Run: python .agent/scripts/search-knowledge.py --help"
echo "   3. Start saving knowledge from your AI chat sessions!"
echo ""
echo "💖 Support this project: https://ko-fi.com/andiupn"
