#
# andy-universal-agent-rules Installer for Windows
# PowerShell one-liner installation
#
# Usage:
#   iwr -useb https://raw.githubusercontent.com/andiupn/andy-universal-agent-rules/main/install.ps1 | iex
#

$ErrorActionPreference = "Stop"

$RepoRaw = "https://raw.githubusercontent.com/andiupn/andy-universal-agent-rules/main"

Write-Host "🚀 Installing andy-universal-agent-rules..." -ForegroundColor Cyan
Write-Host ""

# Check if .agent folder already exists
if (Test-Path ".agent") {
    $confirm = Read-Host "⚠️  .agent folder already exists! Overwrite? (y/N)"
    if ($confirm -ne "y" -and $confirm -ne "Y") {
        Write-Host "❌ Installation cancelled." -ForegroundColor Red
        exit 1
    }
    Remove-Item -Recurse -Force ".agent"
}

# Create .agent folder structure
Write-Host "📁 Creating folder structure..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path ".agent/scripts" | Out-Null
New-Item -ItemType Directory -Force -Path ".agent/memory/entries/gotchas" | Out-Null
New-Item -ItemType Directory -Force -Path ".agent/memory/entries/patterns" | Out-Null
New-Item -ItemType Directory -Force -Path ".agent/memory/entries/decisions" | Out-Null
New-Item -ItemType Directory -Force -Path ".agent/memory/entries/context" | Out-Null
New-Item -ItemType Directory -Force -Path ".agent/context" | Out-Null
New-Item -ItemType Directory -Force -Path ".agent/workflows" | Out-Null

# Download scripts
Write-Host "📥 Downloading scripts..." -ForegroundColor Yellow
$scripts = @(
    "save-knowledge.py",
    "search-knowledge.py",
    "validate-index.py",
    "backup-memory.py",
    "detect-environment.py",
    "sync-agents-stats.py"
)

foreach ($script in $scripts) {
    try {
        Invoke-WebRequest -Uri "$RepoRaw/.agent/scripts/$script" -OutFile ".agent/scripts/$script" -UseBasicParsing
        Write-Host "   ✅ $script" -ForegroundColor Green
    } catch {
        Write-Host "   ⚠️ Failed to download $script" -ForegroundColor Yellow
    }
}

# Download context files
Write-Host "📥 Downloading context files..." -ForegroundColor Yellow
try {
    Invoke-WebRequest -Uri "$RepoRaw/.agent/context/session-init.md" -OutFile ".agent/context/session-init.md" -UseBasicParsing
    Write-Host "   ✅ session-init.md" -ForegroundColor Green
} catch {
    Write-Host "   ⚠️ session-init.md not available" -ForegroundColor Yellow
}

# Download workflows (CORE FEATURE)
Write-Host "📥 Downloading workflows..." -ForegroundColor Yellow
$workflows = @(
    "maintenance.md",
    "maintenance-agent-rules.md",
    "save-from-chat.md",
    "search.md",
    "simpan-pengetahuan-dari-chat.md",
    "simpan-pengetahuan-dari-folder.md"
)

foreach ($workflow in $workflows) {
    try {
        Invoke-WebRequest -Uri "$RepoRaw/.agent/workflows/$workflow" -OutFile ".agent/workflows/$workflow" -UseBasicParsing
        Write-Host "   ✅ $workflow" -ForegroundColor Green
    } catch {
        Write-Host "   ⚠️ Failed to download $workflow" -ForegroundColor Yellow
    }
}

# Create empty index.json
Write-Host "📝 Creating empty knowledge index..." -ForegroundColor Yellow
$indexJson = @'
{
  "version": "1.0.0",
  "lastUpdated": null,
  "totalEntries": 0,
  "categories": {
    "gotchas": {
      "description": "Production bugs & solutions",
      "count": 0,
      "entries": []
    },
    "patterns": {
      "description": "Code patterns that work",
      "count": 0,
      "entries": []
    },
    "decisions": {
      "description": "Architectural decisions",
      "count": 0,
      "entries": []
    },
    "context": {
      "description": "Project context & guides",
      "count": 0,
      "entries": []
    }
  }
}
'@
$indexJson | Out-File -FilePath ".agent/memory/index.json" -Encoding utf8

# Create basic AGENTS.md if not exists
if (-not (Test-Path "AGENTS.md")) {
    Write-Host "📝 Creating AGENTS.md..." -ForegroundColor Yellow
    $agentsMd = @'
# AGENTS.md

> AI Agent Instructions for this project. Powered by andy-universal-agent-rules.

---

## Quick Commands

```powershell
# Save new knowledge
python .agent/scripts/save-knowledge.py --category gotchas "description"

# Search knowledge
python .agent/scripts/search-knowledge.py "keyword"

# Validate index
python .agent/scripts/validate-index.py --fix

# Backup memory
python .agent/scripts/backup-memory.py
```

---

## Knowledge Categories

- **gotchas/** - Production bugs & fixes
- **patterns/** - Working code patterns
- **decisions/** - Architectural decisions
- **context/** - Project guides

---

## Safety Rules

### Always Confirm Before:
- Delete operations
- Git destructive commands
- Package installs

### Never Access:
- `.env` files
- `*.pem`, `*.key` files
- `credentials/` folder

---

*Generated by andy-universal-agent-rules*
*GitHub: https://github.com/andiupn/andy-universal-agent-rules*
'@
    $agentsMd | Out-File -FilePath "AGENTS.md" -Encoding utf8
}

# Run environment detection
Write-Host ""
Write-Host "🔍 Detecting environment..." -ForegroundColor Cyan
try {
    python .agent/scripts/detect-environment.py
} catch {
    Write-Host "⚠️ Python not found. Run 'python .agent/scripts/detect-environment.py' manually." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "✅ Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "📚 Next steps:" -ForegroundColor Cyan
Write-Host "   1. Read AGENTS.md for usage instructions"
Write-Host "   2. Run: python .agent/scripts/search-knowledge.py --help"
Write-Host "   3. Start saving knowledge from your AI chat sessions!"
Write-Host ""
Write-Host "💖 Support this project: https://ko-fi.com/andiupn" -ForegroundColor Magenta
